package br.edu.uepb.tabuleiro;

import java.awt.Font;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import javax.swing.JOptionPane;

/**
 *
 * @author geovanniovinhas
 */
public class TheGame extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
	/**
     * Creates new form Jogo
     */
    public TheGame() {
        initComponents();
        setSize(400,400);
        setLocationRelativeTo(null);
        btn0.setVisible(false);
        List<Integer> numeros = new ArrayList<Integer>();
        for (int i = 1; i < 9 ; i++) { //Sequencia da mega sena
                    numeros.add(i);
          }
        //Embaralhamos os números:
        Collections.shuffle(numeros);
    //btn0.setText("0");
    btn1.setText(Integer.toString(numeros.get(0)));
    btn2.setText(Integer.toString(numeros.get(1)));
    btn3.setText(Integer.toString(numeros.get(2)));
    btn4.setText(Integer.toString(numeros.get(3)));
    btn5.setText(Integer.toString(numeros.get(4)));
    btn6.setText(Integer.toString(numeros.get(5)));
    btn7.setText(Integer.toString(numeros.get(6)));
    btn8.setText(Integer.toString(numeros.get(7)));
   
    /*btn0.setText("1");
    btn1.setText("2");
    btn2.setText("0");
    btn3.setText("4");
    btn4.setText("5");
    btn5.setText("3");
    btn6.setText("6");
    btn7.setText("7");
    btn8.setText("8");*/
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btn0 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        BFS = new javax.swing.JMenuItem();
        DFS = new javax.swing.JMenuItem();
        DFS_Limit = new javax.swing.JMenuItem();
        DFS_Iter = new javax.swing.JMenuItem();
        sobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(3, 3));

        btn0.setText("0");
        btn0.setFont(new Font("Times", Font.PLAIN, 40));
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        getContentPane().add(btn0);

        btn1.setText("1");
        btn1.setFont(new Font("Times", Font.PLAIN, 40));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1);

        btn2.setText("2");
        btn2.setFont(new Font("Times", Font.PLAIN, 40));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2);

        btn3.setText("3");
        btn3.setFont(new Font("Times", Font.PLAIN, 40));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3);

        btn4.setText("4");
        btn4.setFont(new Font("Times", Font.PLAIN, 40));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4);

        btn5.setText("5");
        btn5.setFont(new Font("Times", Font.PLAIN, 40));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn5);

        btn6.setText("6");
        btn6.setFont(new Font("Times", Font.PLAIN, 40));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn6);

        btn7.setText("7");
        btn7.setFont(new Font("Times", Font.PLAIN, 40));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn7);

        btn8.setText("8");
        btn8.setFont(new Font("Times", Font.PLAIN, 40));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        getContentPane().add(btn8);

        jMenu1.setText("Ajuda");

        BFS.setText("BFS");
        BFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFSActionPerformed(evt);
            }
        });
        jMenu1.add(BFS);

        DFS.setText("DFS");
        DFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DFSActionPerformed(evt);
            }
        });
        jMenu1.add(DFS);

        DFS_Limit.setText("DFS Limitada");
        DFS_Limit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DFS_LimitActionPerformed(evt);
            }
        });
        jMenu1.add(DFS_Limit);

        DFS_Iter.setText("DFS Iterativa");
        DFS_Iter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DFS_IterActionPerformed(evt);
            }
        });
        jMenu1.add(DFS_Iter);

        sobre.setText("Sobre");
        sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobreActionPerformed(evt);
            }
        });
        jMenu1.add(sobre);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>                        

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        if(btn1.isVisible() == false){
            String aux = btn2.getText();
            btn2.setText(btn1.getText());
            btn1.setText(aux);
            
            btn2.setVisible(false);
            btn1.setVisible(true);
        }
        if(btn5.isVisible() == false){
            String aux = btn2.getText();
            btn2.setText(btn5.getText());
            btn5.setText(aux);
            
            btn2.setVisible(false);
            btn5.setVisible(true);
        }
    }                                    

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:∂
        if (btn0.isVisible() == false){
            String aux = btn1.getText();
            btn1.setText(btn0.getText());
            btn0.setText(aux);
            
            btn1.setVisible(false);
            btn0.setVisible(true);
           
        }
        if(btn2.isVisible() ==  false){
            String aux = btn1.getText();
            btn1.setText(btn2.getText());
            btn2.setText(aux);
            
            btn1.setVisible(false);
            btn2.setVisible(true);
            
        }
        if(btn4.isVisible() == false){
            String aux = btn1.getText();
            btn1.setText(btn4.getText());
            btn4.setText(aux);
           
            btn1.setVisible(false);
            btn4.setVisible(true);
        }
        
    }                                    

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        if(btn0.isVisible() == false){
            String aux = btn3.getText();
            btn3.setText(btn0.getText());
            btn0.setText(aux);
            
            btn3.setVisible(false);
            btn0.setVisible(true);
       }    
        if(btn4.isVisible() == false){
            String aux = btn3.getText();
            btn3.setText(btn4.getText());
            btn4.setText(aux);
            
            btn3.setVisible(false);
            btn4.setVisible(true);
        }
        
        if(btn6.isVisible() == false){
            String aux = btn3.getText();
            btn3.setText(btn6.getText());
            btn6.setText(aux);
            
            btn3.setVisible(false);
            btn6.setVisible(true);
        }
    }                                    

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        if(btn1.isVisible() ==false){
            String aux = btn0.getText();
            btn0.setText(btn1.getText());
            btn1.setText(aux);
            
            btn0.setVisible(false);
            btn1.setVisible(true);
        }
        
        if(btn3.isVisible() == false){
           String aux = btn0.getText();
            btn0.setText(btn3.getText());
            btn3.setText(aux);
            
            btn0.setVisible(false);
            btn3.setVisible(true);
        }
    }                                    

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        if(btn1.isVisible() ==false){
            String aux = btn4.getText();
            btn4.setText(btn1.getText());
            btn1.setText(aux);
            
            btn4.setVisible(false);
            btn1.setVisible(true);
        }
        if(btn3.isVisible() == false){
           String aux = btn4.getText();
            btn4.setText(btn3.getText());
            btn3.setText(aux);
            
            btn4.setVisible(false);
            btn3.setVisible(true);
        }
        if(btn5.isVisible() == false){
            String aux = btn4.getText();
            btn4.setText(btn5.getText());
            btn5.setText(aux);
           
            btn4.setVisible(false);
            btn5.setVisible(true);
        }
        if(btn7.isVisible() == false){
            String aux = btn4.getText();
            btn4.setText(btn7.getText());
            btn7.setText(aux);
            
            btn4.setVisible(false);
            btn7.setVisible(true);
        }
    }                                    

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        if(btn2.isVisible() == false){
            String aux = btn5.getText();
            btn5.setText(btn2.getText());
            btn2.setText(aux);
            
            btn5.setVisible(false);
            btn2.setVisible(true);
        }
        if(btn4.isVisible() == false){
            String aux = btn5.getText();
            btn5.setText(btn4.getText());
            btn4.setText(aux);
            
            btn5.setVisible(false);
            btn4.setVisible(true);
        }
        if(btn8.isVisible() == false){
            String aux = btn5.getText();
            btn5.setText(btn8.getText());
            btn8.setText(aux);
            
            btn5.setVisible(false);
            btn8.setVisible(true);
        }
        
    }                                    

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        if(btn3.isVisible() == false){
            String aux = btn6.getText();
            btn6.setText(btn3.getText());
            btn3.setText(aux);
            
            btn6.setVisible(false);
            btn3.setVisible(true);
        }
        if(btn7.isVisible() == false){
            String aux = btn6.getText();
            btn6.setText(btn7.getText());
            btn7.setText(aux);
            
            btn6.setVisible(false);
            btn7.setVisible(true);
        }
        
    }                                    

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        if(btn4.isVisible() == false){
            String aux = btn7.getText();
            btn7.setText(btn4.getText());
            btn4.setText(aux);
            
            btn7.setVisible(false);
            btn4.setVisible(true);
        }
        if(btn6.isVisible() == false){
            String aux = btn7.getText();
            btn7.setText(btn6.getText());
            btn6.setText(aux);
            
            btn7.setVisible(false);
            btn6.setVisible(true);
        }
        if(btn8.isVisible() == false){
            String aux = btn7.getText();
            btn7.setText(btn8.getText());
            btn8.setText(aux);
            
            btn7.setVisible(false);
            btn8.setVisible(true);
        }
    }                                    

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {                                     

            // TODO add your handling code here:
            if(btn5.isVisible() == false){
            String aux = btn8.getText();
            btn8.setText(btn5.getText());
            btn5.setText(aux);
                
            btn8.setVisible(false);
            btn5.setVisible(true);
        }
            
            if(btn7.isVisible() == false){
            String aux = btn8.getText();
            btn8.setText(btn7.getText());
            btn7.setText(aux);
            
            btn8.setVisible(false);
            btn7.setVisible(true);
        }
    }                                    

    private void DFSActionPerformed(java.awt.event.ActionEvent evt) {      
    	int index = 0;
        List<Integer> estadoInicial = new ArrayList<>();
        estadoInicial.add(Integer.parseInt(btn0.getText()));
        estadoInicial.add(Integer.parseInt(btn1.getText()));
        estadoInicial.add(Integer.parseInt(btn2.getText()));
        estadoInicial.add(Integer.parseInt(btn3.getText()));
        estadoInicial.add(Integer.parseInt(btn4.getText()));
        estadoInicial.add(Integer.parseInt(btn5.getText()));
        estadoInicial.add(Integer.parseInt(btn6.getText()));
        estadoInicial.add(Integer.parseInt(btn7.getText()));
        estadoInicial.add(Integer.parseInt(btn8.getText()));
        int estado[] = new int[estadoInicial.size()];
        for (int i = 0; i < 9; i++) {
            estado[i] = estadoInicial.get(i);
            if(estado[i] == 0){
                index = i;
            }   
        }
         System.out.println("Matriz Origem : "+Arrays.toString(estado) + "\n" + "------------------------------------\n");
        long time1,time2,time;
        No no = new No(estado);
		no.setIndex(index);
		Profunidade DFS = new Profunidade();
		time1 = System.currentTimeMillis();
		No noSolucao = DFS.resultado(no);
		time2 = System.currentTimeMillis();
		if(noSolucao != null)
		{
			List<No> passos = DFS.listaSolucao(noSolucao);
			String str = "";
			for (No n : passos) {
				str += n.getNum() + " move para " + n.getMove() + "\n";
				System.out.println(n.getNum() + " move para " + n.getMove() + "\n");
			}
			JOptionPane.showMessageDialog(null, str);
			System.out.println("------------------------------------\n" + "total de passos " + passos.size());
			System.out.println("Total de Memoria: " + DFS.getTotalMemoria());
			System.out.println("Total de expansoes: " + DFS.getTotalExpancoes());
			
		time = time2-time1;
			System.out.println("Total do tempo minuto:segundo:milis -> " + new SimpleDateFormat("mm:ss:").format(new Date(time2 - time1)) + time);

			
		}else {
			JOptionPane.showMessageDialog(null, "Nao Achou");
			System.out.println("Nao Achou");
		}
    }                                   

    private void BFSActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
        int index = 0;
        List<Integer> estadoInicial = new ArrayList<>();
        estadoInicial.add(Integer.parseInt(btn0.getText()));
        estadoInicial.add(Integer.parseInt(btn1.getText()));
        estadoInicial.add(Integer.parseInt(btn2.getText()));
        estadoInicial.add(Integer.parseInt(btn3.getText()));
        estadoInicial.add(Integer.parseInt(btn4.getText()));
        estadoInicial.add(Integer.parseInt(btn5.getText()));
        estadoInicial.add(Integer.parseInt(btn6.getText()));
        estadoInicial.add(Integer.parseInt(btn7.getText()));
        estadoInicial.add(Integer.parseInt(btn8.getText()));
        int estado[] = new int[estadoInicial.size()];
        for (int i = 0; i < 9; i++) {
            estado[i] = estadoInicial.get(i);
            if(estado[i] == 0){
                index = i;
            }   
        }
         System.out.println("Matriz Origem : " + Arrays.toString(estado));
        long time1,time2,time;
        No no = new No(estado);
		no.setIndex(index);
		Largura BFS = new Largura();
		time1 = System.currentTimeMillis();
		No noSolucao = BFS.resultado(no);
		time2 = System.currentTimeMillis();
		if(noSolucao != null)
		{
			List<No> passos = BFS.listaSolucao(noSolucao);
			String str = "";
			for (No n : passos) {
				str += n.getNum() + " move para " + n.getMove() + "\n";
			}
			JOptionPane.showMessageDialog(null, str);
			System.out.println("total de passos " + passos.size());
			System.out.println("Total de Memoria: " + BFS.getTotalMemoria());
			System.out.println("Total de expansoes: " + BFS.getTotalExpancoes());
			
		time = time2-time1;
			System.out.println("Total do tempo minuto:segundo:milis -> " + new SimpleDateFormat("mm:ss:").format(new Date(time2 - time1)) + time);

			
		}else {
			JOptionPane.showMessageDialog(null, "Nao Achou");
			System.out.println("Nao Achou");
		}
        
        
    }                                   

    private void sobreActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Quebra Cabeça 8 números \n versão 1.0 \n (c) Copy Rights Geovannio");
    }                                     

    private void DFS_LimitActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    	int index = 0;
        List<Integer> estadoInicial = new ArrayList<>();
        estadoInicial.add(Integer.parseInt(btn0.getText()));
        estadoInicial.add(Integer.parseInt(btn1.getText()));
        estadoInicial.add(Integer.parseInt(btn2.getText()));
        estadoInicial.add(Integer.parseInt(btn3.getText()));
        estadoInicial.add(Integer.parseInt(btn4.getText()));
        estadoInicial.add(Integer.parseInt(btn5.getText()));
        estadoInicial.add(Integer.parseInt(btn6.getText()));
        estadoInicial.add(Integer.parseInt(btn7.getText()));
        estadoInicial.add(Integer.parseInt(btn8.getText()));
        int estado[] = new int[estadoInicial.size()];
        for (int i = 0; i < 9; i++) {
            estado[i] = estadoInicial.get(i);
            if(estado[i] == 0){
                index = i;
            }   
        }
         System.out.println("Matriz Origem : "+Arrays.toString(estado));
        long time1,time2,time;
        No no = new No(estado);
		no.setIndex(index);
		ProfunidadeLimitada DFS_limit = new ProfunidadeLimitada();
		time1 = System.currentTimeMillis();
		No noSolucao = DFS_limit.resultado(no);
		time2 = System.currentTimeMillis();
		if(noSolucao != null)
		{
			List<No> passos = DFS_limit.listaSolucao(noSolucao);
			String str = "";
			for (No n : passos) {
				str += n.getNum() + " move para " + n.getMove() + "\n";
			}
			JOptionPane.showMessageDialog(null, str);
			System.out.println("total de passos " + passos.size());
			System.out.println("Total de Memoria: " + DFS_limit.getTotalMemoria());
			System.out.println("Total de expansoes: " + DFS_limit.getTotalExpancoes());
			
		time = time2-time1;
			System.out.println("Total do tempo minuto:segundo:milis -> " + new SimpleDateFormat("mm:ss:").format(new Date(time2 - time1)) + time);

			
		}else {
			JOptionPane.showMessageDialog(null, "Nao Achou");
			System.out.println("Nao Achou");
		}
    }                                         

    private void DFS_IterActionPerformed(java.awt.event.ActionEvent evt) {    
    	int index = 0;
        List<Integer> estadoInicial = new ArrayList<>();
        estadoInicial.add(Integer.parseInt(btn0.getText()));
        estadoInicial.add(Integer.parseInt(btn1.getText()));
        estadoInicial.add(Integer.parseInt(btn2.getText()));
        estadoInicial.add(Integer.parseInt(btn3.getText()));
        estadoInicial.add(Integer.parseInt(btn4.getText()));
        estadoInicial.add(Integer.parseInt(btn5.getText()));
        estadoInicial.add(Integer.parseInt(btn6.getText()));
        estadoInicial.add(Integer.parseInt(btn7.getText()));
        estadoInicial.add(Integer.parseInt(btn8.getText()));
        int estado[] = new int[estadoInicial.size()];
        for (int i = 0; i < 9; i++) {
            estado[i] = estadoInicial.get(i);
            if(estado[i] == 0){
                index = i;
            }   
        }
         System.out.println("Matriz Origem : " + Arrays.toString(estado));
        long time1,time2,time;
        No no = new No(estado);
		no.setIndex(index);
		ProfunidadeLimitada BFS = new ProfunidadeLimitada();
		time1 = System.currentTimeMillis();
		No noSolucao = BFS.resultado(no);
		time2 = System.currentTimeMillis();
		if(noSolucao != null)
		{
			List<No> passos = BFS.listaSolucao(noSolucao);
			String str = "";
			for (No n : passos) {
				str += n.getNum() + " move para " + n.getMove() + "\n";
			}
			JOptionPane.showMessageDialog(null, str);
			System.out.println("total de passos " + passos.size());
			System.out.println("Total de Memoria: " + BFS.getTotalMemoria());
			System.out.println("Total de expansoes: " + BFS.getTotalExpancoes());
			
		time = time2-time1;
			System.out.println("Total do tempo minuto:segundo:milis -> " + new SimpleDateFormat("mm:ss:").format(new Date(time2 - time1)) + time);

			
		}else {
			JOptionPane.showMessageDialog(null, "Nao Achou");
			System.out.println("Nao Achou");
		}
        
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TheGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TheGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TheGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TheGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TheGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JMenuItem BFS;
    private javax.swing.JMenuItem DFS;
    private javax.swing.JMenuItem DFS_Iter;
    private javax.swing.JMenuItem DFS_Limit;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem sobre;
    // End of variables declaration                   
}
